services:
  db:
    image: postgres:latest
    ports:
      - 5432:5432
    volumes:
     - ~/.rule_engine:/var/lib/postgresql/data
      
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-rule_engine}
      - POSTGRES_USER=${POSTGRES_USER:-rule_engine_USER}
      - POSTGRES_DB=${POSTGRES_DB:-rule_engine_DB}
    networks:
      - app_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    restart: always


  
  backend-base:
    build:
      context: ./backend
      dockerfile: DockerFile
    image: backend:latest

  backend:
    image: backend:latest
    command: ["./start_app.sh"]
    
    ports:
      - 8000:8000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-rule_engine}
      - POSTGRES_USER=${POSTGRES_USER:-rule_engine_USER}
      - POSTGRES_DB=${POSTGRES_DB:-rule_engine_DB}
 
    healthcheck:
      test: ["CMD", "curl", "-f", "http://127.0.0.1:8000"]
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
