# Use an official Python runtime as a parent image
FROM python:3.11

# Set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /backend

# Copy only dependencies related files to the work dir
COPY pyproject.toml poetry.lock ./

# Install Poetry
RUN curl -sSL https://install.python-poetry.org | python3 - && \
    echo "export PATH=$HOME/.local/bin:$PATH" >> ~/.bashrc && \
    . ~/.bashrc && \
    poetry config virtualenvs.create false && \
    poetry install --no-interaction --no-ansi --only=main

# Copy the source and other relevant code to WORKDIR
COPY . .

# Make startup script executable
RUN chmod +x ./start_app.sh
